### DISCUSSION TITLE
Running complex scripts - ADD / COPY script files

### DISCUSSION THREAD

**Discussion by psychemedia** [mmh352/ou-container-builder#34] [Ideas]
I just started having a look at the Dockerfiles I've used previously for adding and seeding postgres databases inside notebook containers, and this sort of fragment is typical:

```
#Run any Postgres database seeding / config routines
ADD config/config_tm351.sql /tmp/postgres/config/config_tm351.sql

USER postgres
#We need to make sure the postgres service is running
# before we try to use it...
RUN service postgresql restart  && \
      psql -f /tmp/postgres/config/config_tm351.sql && \
      service postgresql stop 

#Reset to root user for other build steps
USER root
```

*Note that there is an issue here relating to how to set up the db so that the db files persist by mounting the db directory from the persistent volume which may merit its own discussion topic, but even if we drop the above approach for that reason, it does raise questions about COPY/ADD in the build process. The official postgres container, and the official mongo container, both let you put scripts into an `/docker-entrypoint-initdb.d/` dir that are handled on first run if a db is not found where the db files are mounted [[code](https://github.com/docker-library/postgres/blob/14f13e4b399ed1848fa24c2c1f5bd40c25732bdd/docker-entrypoint.sh#L292)].  Replicating that machinery is a faff, but maybe you already have some related machinery to handle the `content` (I've not checked the code for that yet...)?*.

I notice that you have an `inline` element in the scripts block, which possible means you were also considering a simple `script` block to run commands from a specified file?

But I'll riff a more overengineered approach that just tries to replicate Dockerfile `COPY` and `ADD`, with extra bells and whistles ;-)

To get this sort of thing into the generated Dockerfile, we would need:

- the ability to define the user under which a script is run (add an optional `user` to the script definition)
- the ability to `COPY` or `ADD` files into the container. This could be done in various ways:
  - inside a scripts block;
  - in a `files` or `path(s)` block;
- the ability to set permissions over destination files/directories

For example:

```
scripts:
  pathaction: COPY (required?, case insensitive ideally, inherited but overrideable)
  chmod: optional, applied to all to: destinations/contents, inherited, overrideable
  chown: optional, applied to all to: destinations/contents, inherited overrideable; default: root or $USER
  path:
     from: REQUIRED (validate is Path() (or URL for ADD etc))
     to: REQUIRED
  path:
    action: ADD | COPY (required?, case insensitive ideally, overrides otherwise inherited type)
    from: REQUIRED (validate is Path())
    to: REQUIRED
    autoclean: True [optional, default: False]

files:
  pathaction: ADD | COPY (required?, case insensitive ideally, inherited but overrideable)
  path:
     from: REQUIRED (validate is Path())
     to: REQUIRED 
     action: ADD | COPY (overrides inherited value, case insensitive ideally)
  path:
     from: REQUIRED (validate is Path())
     to: REQUIRED
     chmod: optional (overrides inherited value)
     chown: optional
```

In the Dockerfile template, the `files` should be processed before the `scripts`.

If ADD/COPY were not required, which should be the default (and why?).

In Docker docs, `from`/`to` are `src`/`dest`; from/to are more plain English, src/dest docs conventional;

The `chmod` and `chown` bits would be applied over the destination (may need to identify file or dir).

The `autoclean` in the script could automatically try to rm the copied/added element(s) from `to`. This would probably have to be added as a RUN command after the point in the Dockerfile at which the scripts are processed. (Autoclean may be a nice to have and hard to get right safely; it might also requiring identifying file or dir; user could always explicitly tidy up.)

Both ADD and COPY are useful, not least because ADD can grab from a URL, as well as unpack a tarred/zipped file for you etc.

Before I open issues for any of these elements, I'm happy to discuss / bounce ideas around for other ways of setting up the db etc.
