### ISSUE TITLE
Cmdline configuration structure

### ISSUE THREAD

**Issue by mmh352** [mmh352/ou-container-builder#15]
The command-line statement is an obvious source of errors syntax wise, and also hard to read and a faff to declare? 

```
web_apps:
  - path: openrefine
    cmdline:
      - /var/openrefine/openrefine-3.3/refine
      - -i
      - 0.0.0.0
      - -p
      - "{port}"
      - -d
      - /home/ou-user/OpenRefine
```

Cleaner might be to allow a single long line and then split it into tokens on the space character?

_Originally posted by @psychemedia in https://github.com/mmh352/ou-container-builder/issues/11#issuecomment-832073779_
