### ISSUE TITLE
OpenRefine Demo directory

### ISSUE THREAD

**Issue by mmh352** [mmh352/ou-container-builder#17]
```
web_apps:
  - path: openrefine
    cmdline:
      - /var/openrefine/openrefine-3.3/refine
      - -i
      - 0.0.0.0
      - -p
      - "{port}"
      - -d
      - /home/ou-user/OpenRefine
```

Re: the directory that gets mounted, ideally this would be set into $HOME somewhere where it can persist (eg `/home/ou-user/$CODE-$PRESENTATION/openrefine`). I wasn't sure whether you had a particular convention in mind for that or how the templating might best support it?

_Originally posted by @psychemedia in https://github.com/mmh352/ou-container-builder/issues/11#issuecomment-832073779_
