### ISSUE TITLE
Add name and other metadata to configuration file

### ISSUE THREAD

**Issue by psychemedia** [mmh352/ou-container-builder#7]
At the moment, the module metadata in the config file supports a module code and presentation but no other way to identify the module. It would be useful to be able to give the image a name, not list to distinguish images where a module makes use of several different container types.

```
module:
  code: DEMO
  presentation: 21J
type: jupyter-notebook
content:
  - source: content
    target:
    overwrite: if-unchanged
```

This also raises the question of what other metadata might be useful.

- `description`: a  simple description of the image
- `image-name`: allow user to specify an image name (although I guess you could do this *post hoc* with a `docker` command from the default named created image?)
